### ISSUE TITLE
[Bug]: Could not resolve cacert.pem or php binary when running php artisan native:serve

### ISSUE THREAD

**Issue by kylekanderson** [NativePHP/electron#10]
### What happened?

When running `php artisan native:serve`, I'm receiving the following error message:

> Could not resolve "../../resources/cacert.pem?asset&asarUnpack" from "src/main/index.js"
file: /Users/kyleanderson/Developer/native/vendor/nativephp/electron/resources/js/src/main/index.js

Sometimes, instead of failing to resolve the `cacert.pem` file, it fails to resolve the `php` binary:

> Could not resolve "../../resources/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/kyleanderson/Developer/native/vendor/nativephp/electron/resources/js/src/main/index.js

### How to reproduce the bug

1. `laravel new native-php-test`
2. `cd native-php-test`
3. `composer require nativephp/electron`
4. `php artisan native:install`
5. `php artisan native:serve`

### Package Version

0.1.0

### PHP Version

8.2.8

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS

**Comment by jonsugar** [comment]
Those files are located at:
- `vendor/nativephp/php-bin/cacert.pem`
- `vendor/nativephp/php-bin/bin/mac/arm64/php` or `vendor/nativephp/php-bin/bin/mac/arm64/php` (whichever one is for your macs architecture)

I managed to get native:serve to work by copying them into `vendor/nativephp/electron/resources/js/resources`

Just mentioning in case you want to work-around it for now.

**Comment by vitorleonel** [comment]
@jonsugar I had the same problem then I did what you mentioned, and now I'm getting this new one. Did you get it as well?

<img width="819" alt="image" src="https://github.com/NativePHP/electron/assets/15618005/e050e892-e3a4-4cdc-a71d-46078d0a9ff0">

**Comment by jonsugar** [comment]
@vitorleonel are you using linux? I think linux support is coming soon.

**Comment by vitorleonel** [comment]
@jonsugar Yeah, I remembered it now, actually. I was using Laravel sail and it's Linux, haha.

**Comment by rappasoft** [comment]
> Those files are located at:
> 
> * `vendor/nativephp/php-bin/cacert.pem`
> * `vendor/nativephp/php-bin/bin/mac/arm64/php` or `vendor/nativephp/php-bin/bin/mac/arm64/php` (whichever one is for your macs architecture)
> 
> I managed to get `native:serve` to work by copying them into `vendor/nativephp/electron/resources/js/resources`
> 
> Just mentioning in case you want to work-around it for now.

This does work as a temporary fix!

**Comment by Feelbad-DZ** [comment]
> Those files are located at:
> 
> * `vendor/nativephp/php-bin/cacert.pem`
> * `vendor/nativephp/php-bin/bin/mac/arm64/php` or `vendor/nativephp/php-bin/bin/mac/x86/php` (whichever one is for your macs architecture)
> 
> I managed to get `native:serve` to work by copying them into `vendor/nativephp/electron/resources/js/resources`
> 
> Just mentioning in case you want to work-around it for now.

this fixes the issue with me thank you

**Comment by mpociot** [comment]
This should now be fixed in version 0.1.1
