### ISSUE TITLE
[Bug]: sh: yarn: command not found

### ISSUE THREAD

**Issue by jwktje** [NativePHP/electron#11]
### What happened?

When following the docs in a new Laravel app I get this error;
`sh: yarn: command not found`

It's resolved by installing yarn but it's not mentioned anywhere. 

### How to reproduce the bug

Install a fresh laravel app. Add NativePHP. Try to run the development server

### Package Version

0.1.0

### PHP Version

8.2

### Laravel Version

10.10

**Comment by ahmetbarut** [comment]
Hello,

You need to install yarn

[https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable](You can follow this documentation)

**Comment by jwktje** [comment]
I know, I managed to fix it by installing yarn. I was mostly wondering why yarn is needed instead of npm and why the docs don’t mention it yet. Not a big issue. But I just thought I report it anyway.

**Comment by JunaidQadirB** [comment]
Run `corepack enable` if you have `Node.js >=16.10` 
otherwise, `npm i -g corepack`

Please check [yarn webiste](https://yarnpkg.com/getting-started/install)

**Comment by mpociot** [comment]
The yarn dependency is now removed
