### ISSUE TITLE
[Bug]: TTY mode is not supported on Windows platform.

### ISSUE THREAD

**Issue by noweh** [NativePHP/electron#18]
### What happened?

I run the command php artisan native:install on WampServer for Windows.
After the question "Would you like to start the NativePHP development server (yes/no) [no]:" yes

Error : 
TTY mode is not supported on Windows platform vendor\symfony\process\Process.php:1019

### How to reproduce the bug

On Windows with WampServer,
- Initialize Laravel,
- Add composer require nativephp/electron
- run php artisan native:install

### Package Version

0.1.0

### PHP Version

8.1.13

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by sirosfakhri** [comment]
I'm facing the same error.

I'm using Laravel 10 and PHP 8.2.2.
Also, I use Windows 11.

when I want to start the server, I got the following error:

```
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

   Symfony\Component\Process\Exception\RuntimeException

  TTY mode is not supported on the Windows platform.

  at vendor\symfony\process\Process.php:1019
    1015▕      */
    1016▕     public function setTty(bool $tty): static
    1017▕     {
    1018▕         if ('\\' === \DIRECTORY_SEPARATOR && $tty) {
  ➜ 1019▕             throw new RuntimeException('TTY mode is not supported on Windows platform.');
    1020▕         }
    1021▕
    1022▕         if ($tty && !self::isTtySupported()) {
    1023▕             throw new RuntimeException('TTY mode requires /dev/tty to be read/writable.');

  1   vendor\laravel\framework\src\Illuminate\Process\PendingProcess.php:316
      Symfony\Component\Process\Process::setTty()

  2   vendor\laravel\framework\src\Illuminate\Process\PendingProcess.php:246
      Illuminate\Process\PendingProcess::toSymfonyProcess("yarn run dev")
```

**Comment by mathewberry** [comment]
There is currently no binaries for Windows and is only usable on Mac, I had this same issue, I also tested using the Windows Subsystem for Linux and got a slightly different error, neither work at the moment.

**Comment by sdsoldi** [comment]
+1 windows 11 here.
Waiting for windows binaries :)
