### ISSUE TITLE
an example solution for encrypting php files in electron build

### ISSUE THREAD

**Issue by alperenersoy** [NativePHP/electron#30]
In their talk at Laracon US @mpociot mentioned they are looking for a method to encrypt php files in the electron build. Since it uses its own php binary looks like this situation can be handled with a custom PHP extension that encrypts and decrypts php files. I built a very small working version of it. If it's a silly solution or you have better solutions by now just ignore it.

For more information please check [this repo.](https://github.com/alperenersoy/nativephp-encryption-test)

**Comment by BurakBoz** [comment]
A quote from Ioncube:
```The ionCube Encoder converts PHP source code into bytecode, which can be obfuscated and encrypted for added security, and our unique Dynamic Keys feature uses algorithmic keys that are not stored, providing an extra layer of security for your encoded PHP scripts.```

Decryption is not a wanted thing here it must be one way encrypted (scrambled-descrambled by extension and key) executable bytecode. 

Also can you share your extension source code?

**Comment by alperenersoy** [comment]
@BurakBoz Obviously yes, in this situation, you can extract the encryption key from the binary. For now, looks like it is basically encoding/decoding the code since the key is extractable.  `converting PHP source code into bytecode` means compiling right? I am not sure it can be easily implemented and can work well for different projects. Instead of a constant encryption key, dynamic key generation makes more sense. Or creating an algorithm by chaining encryption algorithms may also be an option. I added the extension source code to the repo. If you have any ideas please share with me.

**Comment by BurakBoz** [comment]
@alperenersoy Firstly, I appreciate your commitment to this discussion and the ideas you've presented so far.

Indeed, converting PHP source code into bytecode means compiling PHP sources into bytecode that can be executed by the PHP virtual machine. For more understanding on this, here's an interesting resource on [how to dump PHP opcodes](https://php.watch/articles/php-dump-opcodes).

It's worth noting, as you've pointed out, this is certainly not an easy task. For anyone willing to explore this further, scrutinizing the source code of opcache could provide valuable insights into how it operates and potentially aid in navigating this challenge.

I should also add an important caveat. Contrary to what one might expect, PHP bytecodes can be reversed back into PHP source code. This poses a security challenge. However, solutions like Ioncube have managed to work around this by modifying or customizing the opcodes, thus hindering the straightforward reversal back to PHP source code.

I'd love to hear more about your thoughts and potential solutions to these challenges. Once again, thank you for your dedication to finding a solution to this issue, and I look forward to our continued discussion.
