### ISSUE TITLE
[Bug]: Class "Native\Laravel\Facades\Notification" not found

### ISSUE THREAD

**Issue by matthewsuan** [NativePHP/electron#37]
### What happened?

tried to add the documented notification and its not working

### How to reproduce the bug

tried to follow the default installation instructions

### Package Version

0.1.1

### PHP Version

8.2

### Laravel Version

10

**Comment by mpociot** [comment]
The package now uses the correct facade: https://github.com/NativePHP/laravel/blob/main/src/Facades/Notification.php
