### ISSUE TITLE
[Bug]: Could not resolve "../../resources/php"

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [NativePHP/electron#40]
### What happened?

I can not run the development server, because **Could not resolve "../../resources/php" from "src/main/index.js"** error is raised and when I opened `main/index.js` I found that when this line **import phpBinary from '../../resources/php'** is interpreted that there is no file or directory called `php` in `resources` directory, so I updated this line to be **import phpBinary from 'electron-builder'**, because `phpBinary` exists in `electron-builder.js` file then I found that is no error raised related to this line, but the next line raised another error says **Could not resolve "../../resources/cacert.pem" from "src/main/index.js**, but this time there is `cacert.pem` file, also there is no `certificate` variable defined at any file

### How to reproduce the bug

When I run `pa native:serve` the **Could not resolve "../../resources/php" from "src/main/index.js"** error is raised.

### Package Version

0.1.1

### PHP Version

8.1.2

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by pandeya0197** [comment]
![image](https://github.com/NativePHP/electron/assets/119948767/21ef6aa5-c86c-4c59-9654-28baf4eb0152)



same issue i am also getting

**Comment by mpociot** [comment]
This is because of the lacking Windows support.

**Comment by pandeya0197** [comment]
thanks for your response i know its not a great place to ask but is there any chance in future it will get a mobile application support also becuase i am php so excited with native php work
