### ISSUE TITLE
[Question] Using remote database

### ISSUE THREAD

**Issue by soixt** [NativePHP/electron#43]
On the presentation it's mentioned about using SQLite and that's fine but what about the remote database with more sensitive data? Does it needs to be configured differently in the whole app as laravel connection or does it bundling do it behind the scenes, I am coming from windows so can't test it yet... Sadly

Thanks

**Comment by mpociot** [comment]
In general you should not directly connect to a remote database in a desktop application as your credentials are available for anyone. You should rather use an API for this

**Comment by soixt** [comment]
Would you maybe create discord for these types of questions, so we don't spam here?
