### ISSUE TITLE
[Bug]: A Javascript error occured in the main process.

### ISSUE THREAD

**Issue by ankitkabra-bacancy** [NativePHP/electron#69]
### What happened?

![image](https://github.com/NativePHP/electron/assets/98305971/b81b6862-cddc-4998-9b46-796eae4feb04)

So previously with 0.3.2 I am able to run windows app with one small error but now after update to 0.3.3 I got above issue when serving using command.

I tried with node version 20,18 but same issue. 

Remove the package and reinstall it and then install native:install and then build it and then trying to serve it but stuck here.

### How to reproduce the bug

- Install fresh laravel 10.
- Install package.
- Then run php artisan native:install
- After that build the windows build using native:build win.
- Try to run native:serve it will give error.

![image](https://github.com/NativePHP/electron/assets/98305971/b81b6862-cddc-4998-9b46-796eae4feb04)

**I used** 

Laravel : v 10.10
Node : Node tried with v20.0 (Working with v0.3.2 [package version]) but not now , Tried with Node vv18.17.0 but not working nither with (0.3.2 or 0.3.3).
NPM : 8.3.2
Platform : Windows
OS : Windows 11 22H2 (build 22621.1992)

### Package Version

0.3.3

### PHP Version

8.1.2

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by andresayac** [comment]
read this please
https://github.com/NativePHP/laravel/issues/96

**Comment by ankitkabra-bacancy** [comment]
Hey thanks @andresayac 

https://github.com/chrisreedio/electron/pull/5

Fix the issue if anyone facing same just go to above PR and file change and replace the whole or selected code from PR 

and run this php artisan native:install and then php artisan native:build win 

and then php artisan native:serve 

it will solve the issue but during build #45  may occur but on serve app will run fine. 

I hope it helps !

**Comment by drhoussem** [comment]
I have the same problem! Why this issue is being closed while it's not fixed in the main repo?

**Comment by ankitkabra-bacancy** [comment]
> I have the same problem! Why this issue is being closed while it's not fixed in the main repo?

As the author of PR said his PR is merged and waiting for release in 0.3.4

**Comment by drhoussem** [comment]
The PR is still WIP here #47

**Comment by NazarAli** [comment]
what you mean RP
