### ISSUE TITLE
[Bug]: Could not resolve "../../resources/php?asset&asarUnpack" from "src/main/index.js"

### ISSUE THREAD

**Issue by ahmetbarut** [NativePHP/electron#9]
### What happened?

I was expecting to run it as described in the documentation but after installation I got an error.

### How to reproduce the bug

I followed the installation steps and after running `php artisan native:serve` it gives the following error.
  
```
  $ php artisan native:serve  

Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…
yarn run v1.22.19
warning package.json: No license field
$ electron-vite dev --watch
vite v4.3.9 building for development...

watching for file changes...

build started...
✓ 2 modules transformed.

build the electron main process successfully


Could not resolve "../../resources/php?asset&asarUnpack" from "src/main/index.js"
file: /Users/ahmetbarut/Desktop/native-php/vendor/nativephp/electron/resources/js/src/main/index.js
vite v4.3.9 building for development...

watching for file changes...

build started...
transforming (1) src/preload/index.js"contextBridge" and "ipcRenderer" are imported from external module "electron" but never used in "src/preload/index.js".
✓ 1 modules transformed.
out/preload/index.js  0.70 kB
built in 56ms. 
```

------

In the Electron package, I looked at the file he specified and he can't find the file he wants to import `../../resources/php?asset&asarUnpack`
You can look at the [file here](https://github.com/NativePHP/electron/blob/main/resources/js/src/main/index.js#L4)
But that [file is not there](https://github.com/NativePHP/electron/tree/main/resources/js/resources)

### Package Version

0.1.0

### PHP Version

8.2.6

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by jonsugar** [comment]
same as #10

**Comment by ThuggerHacks** [comment]
me too, hope it will get fixed s soon as possible

**Comment by rabehasy** [comment]
me too

**Comment by dyadev** [comment]
me too
